### ISSUE TITLE
Google Groups integration with Splunk

### ISSUE THREAD

**Issue by detnon** [alphagov/cyber-security-ggroup-data-to-splunk#1]
Build a simple service for streaming Google Groups audit data into Splunk on a regular basis

https://docs.google.com/document/d/1QDWBtANcgnIChp2vpffZVhBfSF8qLMUIr_HfD-sDv8I/edit#

**Overview**
This will most likely be a lambda that interacts with the google API and then forwards the necessary data onto Splunk. 

To use the google API we'll need to create a google cloud platform project. Since this is going to automate a query for us, we'll need a service account to do this - which we will need to get from IT

**Comment by alice-carr** [comment]
- [x] Create project on Google Cloud platform 
- [x] Get API creds from IT
- [x] Get google service account

**Comment by alice-carr** [comment]
References that may be helpful:
- [python quickstart](https://developers.google.com/admin-sdk/directory/v1/quickstart/python) 
- [google groups reference](https://developers.google.com/admin-sdk/directory/v1/guides/manage-groups)
- [service accounts](https://cloud.google.com/iam/docs/service-accounts)
