### ISSUE TITLE
Add Concourse Pipeline

### ISSUE THREAD

**Issue by alice-carr** [alphagov/cyber-security-ggroup-data-to-splunk#4]
Once we've created the lambda and the terraform, we should deploy these using a concourse pipeline

This issue can be closed when:
- [x] concourse runs tests and validates code
- [x] concourse deploys to demo
- [x] concourse deploys to prod
- [x] concourse has health checks
- [x] the lambdas are working and sending data to splunk in both prod and demo
- [x] the branch has been changed to master in the concourse pipeline

**Comment by alice-carr** [comment]
wip pr for cyber-security-terraform changes here: https://github.com/alphagov/cyber-security-terraform/pull/164

**Comment by alice-carr** [comment]
pipeline canbe found on concourse at ggroups-to-splunk.
Have been testing the pipeline with dev deploy. Mostly fine, last error I saw for the day was:
 'Call to function "filebase64sha256" failed: no file exists at ../../../lambda/get_data_for_google_groups.zip.', will look into this when I'm back in the office next week.

**Comment by alice-carr** [comment]
Need to test that prod has been connected to csls correctly - everything is deployed now so we can do this manually

**Comment by alice-carr** [comment]
Realised that we hadn't routed the prod logs in csls: need to have this PR merged first: https://github.com/alphagov/centralised-security-logging-service/pull/220

**Comment by akinnane** [comment]
I've approved alphagov/centralised-security-logging-service#220.
