### ISSUE TITLE
Write Unit tests 

### ISSUE THREAD

**Issue by detnon** [alphagov/cyber-security-ggroup-data-to-splunk#8]
Unit tests are needed for the ggroup data to splunk script

**Comment by alice-carr** [comment]
There are a lot of third party apis in this, so writing tests is going to be a bit involved. We spiked using [VCR.py](https://vcrpy.readthedocs.io/en/latest/) but we found it quite fiddly and flakey. We would get it working, then it would all break again. We decided to spike to see if we could mock the 3rd party apis instead.

**Comment by alice-carr** [comment]
Mocking third parties is proving to be difficult. After talking to @akinnane we've decided to:
1. refactor the code to make things easier to test and apis easier to mock
2. add better documentation to anything we can't test (i.e - what is the exact shape of the data we're sending and what do we expect back)
